# This is a workflow to aoto merge branches
name: Automerge branches

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout needed branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Merge branches
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git merge add-oas-example
