name: Merge devmasx
on:
  workflow_dispatch:
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge latest -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: latest
          target_branch: main
          github_token: ${{ github.token }}
